This is just a dump of strings, that have to be cleaned up and replaced with "das Biber" in the author field

VON MACHT UND ÜBERGRIFFEN
den Förderungen zu den Inseraten Im Koalitionsvertrag mit den NEOS heißt es, dass künftig Anzeigen an Kri terien wie Innovation, Weiterbildung und journalistische Sorgfalt gebunden sein sollen.
VON AEROBIC-TRAINERIN ZUR NONNE
Anfang an die Challenge Nummer 1 Stillen. Die Legende besagt, es gibt Frauen, bei denen es  Anfang an perfekt klappt. Ich habe sie noch nicht kennengelernt. Tatsache ist, wenn es klappt, ist Stillen eine besondere Form der Bindung und beschert viele wunderschöne Momente. Klappt es nicht, ist es die Hölle. Wunde, blutige Brustwarzen, tausende Versuche, literweise Tränen und unglaublich schmerzhafte Milchstaus. Die Hipp Werbung einer liebevoll stillenden Mutter schwebt vor deinem inneren Auge und du fragst dich Wieso versage ich? Es kostet so viel Kraft, Nerven, Zeit und Freiheit. Und immer, wenn du denkst, du kannst nicht mehr, probierst du noch eine Sache aus und dann geht es einige Zeit weiter. Stillst du zu kurz, bist du eine Rabenmutter. Stillst du zu lange, ein Freak. Stillst du zu früh ab, hast du die Sorge, deinem Kind etwas zu verwehren. Stillst du länger, fragst du dich, wie du es abgewöhnen sollst. Und egal wie du dich entscheidest, dein Umfeld schiebt Kommentare. Dabei gilt heute wie immer Geht’s der Mama gut, geht’s dem Baby gut.
den Kinderfreunden bis zum SPÖ-Parteichef in Wien Michael Ludwig.  Marko Mestrovic
den Schwierigkeiten am Arbeitsmarkt weiß auch Emine Özkan, Sozialarbeiterin und Standortleiterin  Spacelab_girls im Sprungbrett. Die Produktionsschule spacelab ist ein arbeitsmarktpolitisches, breitgefächertes Angebot für Jugendliche zwischen 15 und 24.  „Wir haben beobachtet, dass junge Frauen, die ein Kopftuch tragen, bei der Jobsuche stark benachteiligt werden“, so Özkan. „Sie sind topmotiviert, gut vorbereitet, bewerben sich genauso oft wie andere und bekommen signifikant weniger Chancen.“ Entweder werden die jungen Frauen erst gar nicht zum Bewerbungsgespräch eingeladen, oder man sagt ihnen während des Gesprächs, dass sie die Firma gerne übernimmt, aber nur ohne Kopftuch. „Dabei sind die Mädchen sehr erfinderisch und bereit, Kompromisse einzugehen“, erklärt die 33-Jährige. „Wenn die Firmenfarbe zum Beispiel gelb ist, kaufen sie sich gelbe Kopftücher oder sie binden es anders, greifen zu Hauben und Rollkragen, aber all das bringt oft nichts.“ Manche Mädchen nehmen auch in Kauf, das Kopftuch nur am Weg zum Arbeitsplatz zu tragen und es dann abzulegen, aber selbst das reiche manchen Firmen nicht. Die Sozialarbeiterin hat auch beobachtet, dass die Übergriffe auf MuslimInnen seit 2015 zugenommen haben. „Den Rechtsruck spüren die Jugendlichen sehr Sie werden beschimpft, bespuckt und angegriffen. Dann kommt noch die frustrierende Jobsituation dazu.“ Auch die 20-jährige Yara hat bei einem Bewerbungsgespräch eine Absage bekommen, weil sie ein Kopftuch getragen hat. „Das Hotel meinte, dass ich mit bedeckten Haaren keine Chance habe.“ Getragen hat Yara es insgesamt sechs Jahre, 2016 hat sie es abgelegt. Sie kann sich gut vorstellen, das Kopftuch in ein paar Jahren wieder zu tragen, sollte sich die politische Lage in Österreich wieder verbessern. „Ich werde es aber erst dann aufsetzen, wenn ich mich hier als Muslima wieder sicher fühle.“
einer operativen Öffnung möchte Hayad* nichts wissen. „Wenn ich nicht beschnitten und zugenäht bin, will mich kein Mann“, sagt die 19-Jährige. Sie ist während des Gesprächs schüchtern und unsicher, meidet Augenkontakt. Es ist ihr sichtlich unangenehm, über ihre Beschneidung zu sprechen. Die junge Frau ist vor zwei Jahren alleine nach Österreich geflohen.
Zuhause zum Jugendamt
22.9. - 1.10. ist die Wienwoche 2017 im Gange, und zwar unter dem Thema DOLCE FAR NIENTE. Wer steht nicht auf süßes Nichtstun? Das Wiener Festival kreiert für uns künstlerisch ein Leben jenseits kapitalistischer Produktion. DOLCE FAR NIENTE verlangt danach, Arbeit und Zeit zu revolutionieren. Wir haben für euch zwei Highlights herausgepickt
kleinen Impulsen haben sich Elham Manea und Seyran Ateş schon lange verabschiedet. Die beiden Frauen lernten sich vor einigen Jahren bei einer Diskussion kennen und die Chemie stimmte  Anfang an. Im Frühjahr dieses Jahres einigten sie sich auf eine muslimische Revolution  innen Als Co-Gesellschafterinnen eröffnen sie diesen Monat die liberale Ibn Rushd-Goethe-Moschee in Berlin. Elham Manea, eine schweizerisch-jemenitischen Politologin und Imamin und der Islamwissenschafter Dr. Abdel Hakim Ourghi, leiten Seite an Seite das Freitagsgebet. Und das vor einer gemischtgeschlechtlichen Gruppe. Sie auf Arabisch, er auf Deutsch. Danach hält Ateş, Imamin in Ausbildung, eine Predigt über die Liebe. Üblicherweise sind Frauen und Männer in Moscheen räumlich einander getrennt. Ein Zustand, den die deutsch-türkische Menschenrechtsanwältin Ateş so nicht hinnehmen wollte “Ich brauche meine Spiritualität und die will ich mir nicht in einem Hinterzimmer holen müssen. Eine Moschee, in der nur Männer sind, spiegelt die Realität wieder die Frau hat keinen sozialen Status. Weder in der Moschee, noch in der Gesellschaft.” Das Ziel ist klar Die männliche Monopolstellung im Leiten  Gebeten soll ein Ende haben. Frauen sollen ihren Platz im Hauptraum der Moschee finden und folglich auch in der Gesellschaft. Doch es geht nicht nur darum, eine Imamin zu haben und schon gar nicht Männer ganz abzulösen. Nach der Vision der beiden Imaminnen beten Frauen und Männer Seite an Seite. Die Botschaft lautet “Wir sind gleich vor Gott. Gleich vor dem Gesetz. Gleich in der Gesellschaft.” Also mietet Ateş Räumlichkeiten einer evangelischen Kirchengemeinde und eröffnet ihre liberale Moschee, die Sunniten, Aleviten, Schiiten und Sufis gleichermaßen offensteht. Auch Homosexuelle und Frauen ohne Kopftuch sind willkommen.
Orientierungsläufen und Abseilen über Zeltbauen bis hin zu Schießübungen und Nahkampf ist wirklich alles dabei. Auf Facebook könnt ihr euch alle Videos noch einmal ansehen. Hier haben wir für euch die TOP 3 herausgesucht
Schleppern erpresst, vom IS vergewaltigt
A wie Arabisch bis Ö wie Öffnungszeiten Die wichtigsten Fakten
den rund 8900 Inhaftierten Österreichweit sind 1700 da Muslime. Der 29Jährige hat seine Masterarbeit an der Uni-Wien in Islamischer Religionspädagogik geschrieben. Titel der Arbeit „Junge muslimische Häftlinge in österreichischen Justizanstalten und die Bedeutung der Islamischen Gefängnisseelsorge“
Kammers Gnaden
Kupplers Gnaden
März bis September hat Sani Saison, vielmehr sein Bauch. Der Perser trägt im Sommer ein perfektes Sixpack. Dafür achtet er in diesen Monaten besonders auf seine Ernährung. Seit zwei Jahren macht er die „Low-Carb- Diät“ Er reduziert  Nudeln,  Reis, Kartoffeln und Weißbrot. Stattdessen gibt es Müsli mit Banane, Thunfischsalat und natürlich ganz viele Karotten, Gurken und Salat. Auch Säfte lässt er weg, stattdessen nur stilles Wasser. Diese Diät gefällt Sani am besten. „Ich brauche nicht zu verzichten“, sagt er. Außerdem spürt er den Effekt Die Antriebslosigkeit in der Früh sei weg, die Haut schöner, er sei fitter und schwitze weniger. „Der Körpergeruch geht zurück.“ Man soll es aber nicht übertreiben, weiß Sani. Vorletztes
links nach rechts Alexander, Dipl.Ing. Marko Stijaković , Ivana und Milinko
Fiction zu Pulp und zurück. Abu Bogumil Balkansky fährt eine Runde mit dem Taxi
der Mehrheit zur Minderheit geworden
Interpol gesucht
den 84 Millionen Einwohnerinnen Irans sind 60 Prozent unter 30 Jahre alt, es handelt sich also um eine sehr junge Bevölkerung. Es ist eine Generation, die nur das Leben in der islamischen Republik kennt. Auch die iranische GenZ ist im Internet aufgewachsen, obwohl Social-Media-Seiten wie Instagram oder TikTok nur mit VPNs erreichbar sind. Sie haben gelernt, Regeln zu umgehen, weil sie so aufgewachsen sind. Sie bewegen sich somit in Sphären, die die Regierung nicht kontrollieren kann. Sie wissen, durch Kontakt zu Verwandten im Ausland, aber auch durch Serien und Filme, wie andere Menschen in Freiheit leben.  “Die Generation der Protestierenden hat sich geändert”, erklärt Mohsen. “Ihr moderner Lebensstil unterscheidet sich  sehr vom Lebensstil, den das Regime propagiert.” Der GenZ stößt dem Regime schon seit einiger Zeit sauer auf, neben den strengen Gesetzen und Regeln kommt der wirtschaftliche Druck hinzu die Inflation im Iran beträgt 52,2% , die Jugendarbeitslosigkeit bei 15-24 Jährigen liegt bei 24,5%.
dsa Biber
Novosibirsk nach Wien
250 auf 1200 Euro
Wien bis Dornbirn
Wien nach Shenzhen
der Schulbank in die Disko
Kopf bis Fuß